[package]
authors = ["Christopher Brickley <brickley@gmail.com>"]
description = "A rust crate for sending messages to Slack via webhooks."
homepage = "https://github.com/frostly/rust-slack"
keywords = ["slack", "webhook", "hook", "messaging"]
license = "MIT/Apache-2.0"
name = "slack-hook"
readme = "README.md"
repository = "https://github.com/frostly/rust-slack"
version = "0.4.0"

[dependencies]
chrono = ">= 0.3.1"
curl = ">= 0.3.0, < 0.5.0"
hex = "0.2.0"
log = "0.3.6"
error-chain = "~0.10"
serde = "1"
serde_derive = "1"
serde_json = "1"
url_serde = "0.2"
url = ">= 1.2.0, < 1.5.0"

[dependencies.clippy]
optional = true
version = "^0.0"
